name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build:test

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: ${{ github.workspace }}/build
  lint:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Lint
        run: npm run lint

  tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
        run: npm run test

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Integration - testcafe
        id: testcafe
        if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
        run: npm run integration:headless

      - name: Upload Artifact
        if: ${{ failure() && steps.testcafe.outcome == 'failure' }}
        uses: actions/upload-artifact@v3
        with:
          name: testcafe-fail-screenshots
          path: artifacts
          if-no-files-found: ignore
          retention-days: 5

  synpress-e2e:
    name: Synpress e2e test
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: tests
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Integration - Synpress
        if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: npm run integration:headful:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          spec: tests/e2e/specs/*
        env:
          CYPRESS_PROJECT_ID: "trkg83"
          CYPRESS_RECORD_KEY: "5fd3babb-9ca9-4743-a9c5-1e8164dbf9ef"
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress
